clear all
close all
load('all_sub_resp_contacts.mat')
load('start_pho_only_contacts.mat')
load('start_sem_only_contacts.mat')
load('start_both_contacts_p.mat')
load('start_both_contacts_s.mat')

save_folder = [pwd, filesep];

% **1️⃣ Ensure all brain region names are of char type**
all_regions = cellfun(@char, all_sub_resp_contacts(:,4), 'UniformOutput', false);
start_pho_regions = cellfun(@char, start_pho_only_contacts(:,6), 'UniformOutput', false);
start_sem_regions = cellfun(@char, start_sem_only_contacts(:,6), 'UniformOutput', false);
start_both_p_regions = cellfun(@char, start_both_contacts_p(:,6), 'UniformOutput', false);
start_both_s_regions = cellfun(@char, start_both_contacts_s(:,6), 'UniformOutput', false);

% **2️⃣ Get all unique brain regions (based on all_sub_resp_contacts)**
unique_all_regions = unique(all_regions); 

% **3️⃣ Initialize storage array**
region_counts = cell(length(unique_all_regions), 6); 
region_counts(:,1) = unique_all_regions; % First column: brain region names

% **4️⃣ Count the number of electrodes in each brain region for each variable**
% ---- Count the number of electrodes in `all_sub_resp_contacts` ----
all_region_numbers = zeros(length(unique_all_regions), 1);
for i = 1:length(unique_all_regions)
    all_region_numbers(i) = sum(strcmp(all_regions, unique_all_regions{i}));
end
region_counts(:,2) = num2cell(all_region_numbers); % Store in the 2nd column

% ---- Count the number of electrodes in `start_pho_only_contacts` ----
pho_region_numbers = zeros(length(unique_all_regions), 1);
for i = 1:length(unique_all_regions)
    pho_region_numbers(i) = sum(strcmp(start_pho_regions, unique_all_regions{i}));
end
region_counts(:,3) = num2cell(pho_region_numbers); % Store in the 3rd column

% ---- Count the number of electrodes in `start_sem_only_contacts` ----
sem_region_numbers = zeros(length(unique_all_regions), 1);
for i = 1:length(unique_all_regions)
    sem_region_numbers(i) = sum(strcmp(start_sem_regions, unique_all_regions{i}));
end
region_counts(:,4) = num2cell(sem_region_numbers); % Store in the 4th column

% ---- Count the number of electrodes in `start_both_contacts_p` ----
both_p_region_numbers = zeros(length(unique_all_regions), 1);
for i = 1:length(unique_all_regions)
    both_p_region_numbers(i) = sum(strcmp(start_both_p_regions, unique_all_regions{i}));
end
region_counts(:,5) = num2cell(both_p_region_numbers); % Store in the 5th column

% ---- Count the number of electrodes in `start_both_contacts_s` ----
both_s_region_numbers = zeros(length(unique_all_regions), 1);
for i = 1:length(unique_all_regions)
    both_s_region_numbers(i) = sum(strcmp(start_both_s_regions, unique_all_regions{i}));
end
region_counts(:,6) = num2cell(both_s_region_numbers); % Store in the 6th column

save([save_folder,'region_counts','.mat'],'region_counts');

%% Merge detailed anatomical regions into 14 macro-regions

% num_all_p_s:
% Column 1 = all responsive contacts
% Column 2 = phonology-only contacts
% Column 3 = semantic-only contacts
% Column 4 = both-selective contacts

macro_region_names = { ...
    'HG'; ...
    'Insula'; ...
    'pmSTG'; ...
    'MTG'; ...
    'ITG'; ...
    'PCC'; ...
    'Cuneus'; ...
    'MFG'; ...
    'IFG'; ...
    'Sensorimotor'; ...
    'MTL'; ...
    'aSTG'; ...
    'Temporal Pole'; ...
    'IPL'};

macro_region_defs = cell(14,1);

% 1. HG
macro_region_defs{1} = { ...
    'transverse temporal gyrus L', ...
    'transverse temporal gyrus R'};

% 2. Insula
macro_region_defs{2} = { ...
    'insula - anterior L', ...
    'insula - anterior R', ...
    'insula - posterior L', ...
    'insula - posterior R'};

% 3. pmSTG
macro_region_defs{3} = { ...
    'superior temporal gyrus - middle L', ...
    'superior temporal gyrus - middle R', ...
    'superior temporal gyrus - posterior L', ...
    'superior temporal gyrus - posterior R'};

% 4. MTG
macro_region_defs{4} = { ...
    'middle temporal gyrus - anterior L', ...
    'middle temporal gyrus - anterior R', ...
    'middle temporal gyrus - dorsoposterior L', ...
    'middle temporal gyrus - dorsoposterior R', ...
    'middle temporal gyrus - middle L', ...
    'middle temporal gyrus - middle R', ...
    'middle temporal gyrus - ventroposterior L'};

% 5. ITG
macro_region_defs{5} = { ...
    'fusiform gyrus - anterior L', ...
    'fusiform gyrus - anterior R', ...
    'fusiform gyrus - posterior L', ...
    'fusiform gyrus - posterior R', ...
    'inferior temporal gyrus - anterior L', ...
    'inferior temporal gyrus - anterior R', ...
    'inferior temporal gyrus - middle L', ...
    'inferior temporal gyrus - posterior L', ...
    'inferior temporal gyrus - posterior R'};

% 6. PCC
macro_region_defs{6} = { ...
    'cingulate gyrus - posterior L', ...
    'cingulate gyrus - posterior R'};

% 7. Cuneus
macro_region_defs{7} = { ...
    'cuneus - anterior L', ...
    'cuneus - posterior L', ...
    'precuneus - inferior L', ...
    'precuneus - inferior R', ...
    'precuneus - superior L', ...
    'precuneus - superior R'};

% 8. MFG
macro_region_defs{8} = { ...
    'middle frontal gyrus - anterior L', ...
    'middle frontal gyrus - posterior L', ...
    'middle frontal gyrus - posterior R'};

% 9. IFG
macro_region_defs{9} = { ...
    'pars opercularis - inferior L', ...
    'pars opercularis - inferior R', ...
    'pars opercularis - superior L', ...
    'pars opercularis - superior R', ...
    'pars triangularis - middle L', ...
    'pars triangularis - posterior R'};

% 10. Sensorimotor
macro_region_defs{10} = { ...
    'paracentral lobule R', ...
    'postcentral gyrus - inferior L', ...
    'postcentral gyrus - inferior R', ...
    'postcentral gyrus - superio R', ...
    'postcentral gyrus - superior L', ...
    'postcentral gyrus - superior R', ...
    'precentral gyrus - inferior L', ...
    'precentral gyrus - inferior R', ...
    'precentral gyrus - superior L', ...
    'precentral gyrus - superior R'};

% 11. MTL
macro_region_defs{11} = { ...
    'Amygdala L', ...
    'Amygdala R', ...
    'Hippocampus L', ...
    'Hippocampus R', ...
    'parahippocampal gyrus L', ...
    'parahippocampal gyrus R'};

% 12. aSTG
macro_region_defs{12} = { ...
    'superior temporal gyrus - anterior L', ...
    'superior temporal gyrus - anterior R'};

% 13. Temporal Pole
macro_region_defs{13} = { ...
    'temporal pole L', ...
    'temporal pole R'};

% 14. IPL
macro_region_defs{14} = { ...
    'angular gyrus - anterior L', ...
    'angular gyrus - anterior R', ...
    'angular gyrus - middle L', ...
    'angular gyrus - middle R', ...
    'angular gyrus - posterior L', ...
    'angular gyrus - posterior R', ...
    'supramarginal gyrus - anterior L', ...
    'supramarginal gyrus - anterior R', ...
    'supramarginal gyrus - posterior L'};

% Extract region names and numerical counts from region_counts
region_names = cellfun(@char, region_counts(:,1), 'UniformOutput', false);
region_names = cellfun(@strtrim, region_names, 'UniformOutput', false);

region_nums = zeros(size(region_counts,1), 5);

for c = 2:6
    for i = 1:size(region_counts,1)
        region_nums(i,c-1) = double(region_counts{i,c});
    end
end

% region_nums column 1 = all responsive contacts
% region_nums column 2 = phonology-only contacts
% region_nums column 3 = semantic-only contacts
% region_nums column 4 = both_p contacts
% region_nums column 5 = both_s contacts

num_all_p_s = zeros(length(macro_region_names), 4);
matched_flag = false(size(region_names));

for r = 1:length(macro_region_names)

    sub_regions = macro_region_defs{r};

    idx = ismember(region_names, sub_regions);
    matched_flag = matched_flag | idx;

    num_all_p_s(r,1) = sum(region_nums(idx,1));
    num_all_p_s(r,2) = sum(region_nums(idx,2));
    num_all_p_s(r,3) = sum(region_nums(idx,3));

    % both_p and both_s usually represent the same both-selective contacts.
    % Using their sum may double-count the same contacts.
    both_p_count = sum(region_nums(idx,4));
    both_s_count = sum(region_nums(idx,5));

    if both_p_count ~= both_s_count
        warning('%s: both_p and both_s counts are inconsistent. Please check whether a union should be used.', macro_region_names{r});
    end

    num_all_p_s(r,4) = max(both_p_count, both_s_count);

end

% Save the merged region-level counts
save([save_folder, 'num_all_p_s.mat'], ...
    'num_all_p_s', ...
    'macro_region_names', ...
    'macro_region_defs');

% Display the results for inspection
disp('Rows:');
disp(macro_region_names);

disp('Columns: all responsive, phonology only, semantic only, both');
disp(num_all_p_s);

% Display regions that were not assigned to any of the 14 macro-regions
unmatched_regions = region_names(~matched_flag);

disp('The following regions were not assigned to any macro-region:');
disp(unmatched_regions);